export type ActiveView =
  | "dashboard"
  | "debts"
  | "debtsStatement"
  | "incomes"
  | "payments"
  | "incomeReceipts"
  | "categories"
  | "creditCards"
  | "users"
  | "profile"
  | "plans"
  | "forecast"
  | "calendar"
  | "faq";
