export const LOGIN_IDENTIFIER_MIN_LENGTH = 3;
export const LOGIN_IDENTIFIER_MAX_LENGTH = 30;

export const LOGIN_PASSWORD_MIN_LENGTH = 8;
export const LOGIN_PASSWORD_MAX_LENGTH = 20;

export const PASSWORD_RECOVERY_CODE_LENGTH = 5;
